##
## ec2-template
##
AWSTemplateFormatVersion: "2010-09-09"
Description: ec2-template

# --------------------------
# Parameters
#---------------------------
Parameters:
  TagKey:
    Type: String
    Default: created-by
  TagValue:
    Type: String
    Default: "keiichi tsuda"

# --------------------------
# Resources
#---------------------------
Resources:
  # KeyPair for SSH access
  # private key will be stored in a parameter store with the name: /ec2/keypair/{key_pair_id}.
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties: 
      KeyName: ec2-key
      Tags: 
        - Key: !Sub ${TagKey}
          Value: !Sub ${TagValue}
  # SecurityGroup for EC2
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for EC2
      GroupName: ec2-sg
      VpcId: !ImportValue vpc-base
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: ec2-sg
        - Key: !Sub ${TagKey}
          Value: !Sub ${TagValue}
  # EC2
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs: 
            DeleteOnTermination: true
            Encrypted: true
            VolumeSize: 10
            VolumeType: gp2
      ImageId: ami-0bba69335379e17f8
      InstanceType: t2.micro
      KeyName: !Ref KeyPair
      SecurityGroupIds: 
        - !GetAtt SecurityGroup.GroupId
      SubnetId: !ImportValue pubnet01
      Tags: 
        - Key: Name
          Value: ec2-instance
        - Key: !Sub ${TagKey}
          Value: !Sub ${TagValue}